import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Article.module.css'
import Link from 'next/link';
import CodeViewer from '../components/templateCode.js';

const inter = Inter({ subsets: ['latin'] })


export default function Esqueleto() {
  return (
    <>
      <Head>
        <title>CodeXLearn | Esqueleto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.article}>
          <h1>Esqueleto</h1>
          <h2>Template</h2>
          <p>
            Un codigo en C++ es bastante corto, aqui se muestra como se implementa
            un hola mundo clasico.
          </p>
          <CodeViewer/>
        </div>
      </main>
    </>
  )
}
