import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Article.module.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })


export default function Variables() {
  return (
    <>
      <Head>
        <title>CodeXLearn | Variables</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
          <p>Variables</p>
      </main>
    </>
  )
}
