import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Article.module.css'
import Link from 'next/link';
import TablaTiposDatos from '../components/tiposDato.js';

const inter = Inter({ subsets: ['latin'] })


export default function Variables() {
  return (
    <>
      <Head>
        <title>CodeXLearn | Variables</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.article}>
          <h1>Variables</h1>
          <h2>Que son?</h2>
          <p>
            Las variables en programación son espacios en memoria que pueden tomar
            cualquier valor siempre del mismo tipo, mientras que en programación
            competitiva las vemos como cajas, en las cuales podemos guardar
            información siempre del mismo tipo.
          </p>
          <TablaTiposDatos/>
        </div>
      </main>
    </>
  )
}
